!!python/object/new:easydict.EasyDict
state:
  numProcessors: -1
  numPeriods: 25
  omega0: 5
  samplingFreq: 100
  minF: 1
  maxF: 25
  tSNE_method: barnes_hut
  perplexity: 32
  embedding_batchSize: 30000
  maxOptimIter: 100
  trainingSetSize: 5000
  maxNeighbors: 200
  kdNeighbors: 5
  training_perplexity: 20
  training_numPoints: 10000
  minTemplateLength: 1
  waveletDecomp: true
  useGPU: -1
  n_neighbors: 15
  train_negative_sample_rate: 5
  embed_negative_sample_rate: 1
  min_dist: 0.1
  umap_output_dims: 2
  n_training_epochs: 1000
  rescale_max: 100
  method: TSNE
  projectPath: content/trial1_mmpy220720_115500
  pcaModes: 2
dictitems:
  numProcessors: -1
  numPeriods: 25
  omega0: 5
  samplingFreq: 100
  minF: 1
  maxF: 25
  tSNE_method: barnes_hut
  perplexity: 32
  embedding_batchSize: 30000
  maxOptimIter: 100
  trainingSetSize: 5000
  maxNeighbors: 200
  kdNeighbors: 5
  training_perplexity: 20
  training_numPoints: 10000
  minTemplateLength: 1
  waveletDecomp: true
  useGPU: -1
  n_neighbors: 15
  train_negative_sample_rate: 5
  embed_negative_sample_rate: 1
  min_dist: 0.1
  umap_output_dims: 2
  n_training_epochs: 1000
  rescale_max: 100
  method: TSNE
  projectPath: content/trial1_mmpy220720_115500
  pcaModes: 2
